travis:
  secure:
    BINSTAR_TOKEN: Qy2b1HuoGi3YsyCDE0VyHbT6+4nvNV0qbkB9Opd+Ird2srVC5Kt7ogdnN31OaolLsi9lkzVjtaYeGbWTJEF17MBFqrildQyG6Isjqr0tEMUMKma0fPD3mlpK8TaN9hyAIvLy8+4BuOcPBJa+bNFtNpgAUA8mobzdF6lXz5LygFfutSxk0ZO8OHFan/8x6pqMKWN7MzMIZR0NLbUSRTbmky3mQ1o2O8TR6+RC5QMHO8g07CGggL2snWdkcdRLCY5NStJrkq7/zmhupSXH73scg7b2FgAfo/p/OFchH7r89JLK60d0xn/bR+xv18j3r1Q04mzLoMbUHk9fvipSBV/GQBjbPpi7+dhqdMCC+4/tPpbsQbJk5R3SrOhEcQeXFtv5nDOV4qVxtlsTqmKBhs4dJxzeh9bQSlxzStEKdeXtcFh1cymw5jaMehaB37H6+oOK79wkcYhKsxzC+R45Jp7RaernDziRk6vYR3NC8MpKw1XJZ7qSjw521MAc2l5naMYnS/EbJ9Clg66C8/sJ/atKRVxOmlxq7NQ9PdkzGCIH14k6D+pGXwko3n9LM/PjzwpFhDS8Ij3jBzGhNxrNBxnsdFGRKARUtpLr17NLWkipoCgp8IgMo+5ZfsuBkq1tGizNcBrDS1/zk/JT7ck4yY8BdHwE6bbSHCz7tGlSfJTrg2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
